<?php //include config
include 'app/views/admin/includes/admin-header.phtml';

//if not logged in redirect to login page
//if(!$user->is_logged_in()){ header('Location: login.php'); }
?>
<meta HTTP-EQUIV="Pragma" content="no-cache">
<meta HTTP-EQUIV="Expires" content="-1" >
<div id="wrapper">

	<h2>Add Post</h2>
    <ul id='adminmenu'>
        <li><a href='/adBlog/index'>post</a></li>
        <li><a href="/adBlog/categories">categories</a></li>
    </ul>
    <div class='clear'></div>
    <hr />
	<?php

	//check for any errors
	if(isset($this->view_data['error'])){
		foreach($this->view_data['error'] as $error1){
			echo '<p class="error">'.$error1.'</p>';
		}
	}
	?>

	<form action='' method='post' enctype="multipart/form-data" onsubmit=" return submit()">

		<p><label>Title</label><br />
            <textarea class="summernote"  name='postTitle'><?php if(isset($error)){ echo $_POST['postTitle'];}?></textarea>></p>

		<p><label>Description</label><br />
		<textarea class="summernote" name='postDesc' cols='60' rows='10'><?php if(isset($error)){ echo $_POST['postDesc'];}?></textarea></p>

		<p><label>Content</label><br />
		<textarea class="summernote" name='postCont' cols='60' rows='10'><?php if(isset($error)){ echo $_POST['postCont'];}?></textarea></p>

        <p<label for="image">Image</label>
        <input type="file" name="image" id="image" placeholder="Choose an image to upload" maxlength="255" /></p>

        <fieldset>
            <legend>categories</legend>
            <?php foreach ($this->view_data['categories'] as $category){
         echo '<input type="checkbox" name="cat_list[]"';
           echo 'value="'.$category.'"><label>'.$category.'</label><br>';
             }
             ?>
        </fieldset>

		<p><input type='submit' name='submit' value='Submit'></p>

	</form>

</div>
<script>
    $(document).ready(function() {
        $('.summernote').summernote({height:300});
    });
    function submit() {
        $('.summernote').each( function() {
            $(this).html($(this).summernote('code'));
        });
    }
</script>
