<?php include 'app/views/admin/includes/admin-header.phtml'; ?>

<div id="wrapper">
    <h1>Blog</h1>
    <ul id='adminmenu'>
        <li><a href='/adBlog/index'>post</a></li>
        <li><a href="/adBlog/categories">categories</a></li>
    </ul>
    <div class='clear'></div>
    <hr />
    <table>
    <tr>
        <th>Title</th>
        <th>Action</th>
    </tr>
        <?php
                foreach ($this->view_data['categories'] as $category) {
            echo '<tr>';

            echo '<td>' . $category . '</td>';



            ?>
            <td>
                <a href="<?php echo '/adBlog/editCat/'. $category; ?>">Edit</a> |
                <a href="javascript:delcat('<?php echo $category; ?>')">Delete</a>
            </td>
        <?php
                echo '</tr>';
            }
            ?>
    </table>
    <br><br>
    <p><a href="/adBlog/addCat">Add category</a></p>

</div>
<script language="JavaScript" type="text/javascript">
    function delcat(name)
    {
        if (confirm("Are you sure you want to delete '" + name + "'"))
        {
            window.location.href = '/adBlog/deleteCat/' + name;
        }
    }
</script>
    <?php include 'app/views/includes/footer.phtml'?>
