<?php include 'app/views/admin/includes/admin-header.phtml'; ?>
<div class="tm-contact-img-container" style="background-image: url('<?php echo $this->view_data['headImage'];?>');">
</div>
<div class="input-group mb-3">
    <input type="file" class="custom-file-input" id="contact"><br>
    <button onclick="saveHeadImage('contact')">save</button>
</div>
<section class="tm-section">
    <div class="container-fluid" id="contact">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">

                <section>
                    <h3 class="tm-gold-text tm-form-title 1"><?php echo $this->view_data['contact'][0]['title']?></h3>
                    <p class="tm-form-description 1"><?php echo $this->view_data['contact'][0]['content']?></p>

                    <button onclick="edit('1')">edit</button>
                    <button onclick="save('1')">save</button>
                    <form action="index.html" method="post" class="tm-contact-form">
                        <div class="form-group">
                            <input type="text" id="contact_name" name="contact_name" class="form-control" placeholder="Name"  required/>
                        </div>
                        <div class="form-group">
                            <input type="email" id="contact_email" name="contact_email" class="form-control" placeholder="Email"  required/>
                        </div>
                        <div class="form-group">
                            <input type="text" id="contact_subject" name="contact_subject" class="form-control" placeholder="Subject"  required/>
                        </div>
                        <div class="form-group">
                            <textarea id="contact_message" name="contact_message" class="form-control" rows="6" placeholder="Message" required></textarea>
                        </div>

                        <button type="submit" class="tm-btn">Submit</button>
                    </form>
                </section>


            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-contact-right">
                <section class="tm-margin-t-mid tm-map-section">
                    <h3 class="tm-gold-text tm-form-title 2"><?php echo $this->view_data['contact'][1]['title']?></h3>

                    <div id="google-map"><img src="/app/helpers/img/map.png"  id="google-map"></div>

                    <p class="tm-form-description 2"><?php echo $this->view_data['contact'][1]['content']?></p>

                    <button onclick="edit('2')">edit</button>
                    <button onclick="save('2')">save</button>
                </section>
            </div>
        </div>

    </div>
</section>
<script src="/app/helpers/js/contact.js"></script>
<?php include 'app/views/includes/footer.phtml'?>
