<?php include 'app/views/admin/includes/admin-header.phtml'; ?>
<div class="tm-about-img-container" style="background-image: url('<?php echo $this->view_data['headImage'];?>');">
</div>

<div id="wrapper">
    <h1>Blog</h1>
    <ul id='adminmenu'>
        <li><a href='/adBlog/index'>post</a></li>
        <li><a href="/adBlog/categories">categories</a></li>
    </ul>
    <div class='clear'></div>
    <hr />
    <table>
    <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Action</th>
    </tr>
        <?php
                foreach ($this->view_data['posts'] as $post) {
            echo '<tr>';
            echo '<td>' . $post['title'] . '</td>';
            echo '<td>' . date('j F Y', $post['publicationDate']) . '</td>';


            ?>
            <td>
                <a href="<?php echo '/adBlog/editPost/'.$post['id']; ?>">Edit</a> |
                <a href="javascript:delpost('<?php echo $post['id']; ?>')">Delete</a>
            </td>
        <?php
                echo '</tr>';
            }

            ?>
    </table>
    <br><br>
    <p><a href='/adBlog/addPost'>Add Post</a></p>

</div>
<script language="JavaScript" type="text/javascript">
    function delpost(id)
    {
        if (confirm("Are you sure you want to delete this"))
        {
            window.location.href = '/adBlog/deletePost/' + id;
        }
    }
</script>    <?php include 'app/views/includes/footer.phtml'?>
