<?php
include 'app/views/admin/includes/admin-header.phtml';
?>
<meta HTTP-EQUIV="Pragma" content="no-cache">
<meta HTTP-EQUIV="Expires" content="-1" >
<div id="wrapper">

	<h2>Edit Admin</h2>
    <div class='clear'></div>
    <hr />
    <?php

    //check for any errors
    if(isset($this->view_data['error'])){
        foreach($this->view_data['error'] as $error1){
            echo '<p class="error">'.$error1.'</p>';
        }
    }
    ?>


    <form action='' method='post'>
        <p><label>Username</label><br />
            <input type='text' name='username' value=''></p>

        <p><label>Password (only to change)</label><br />
            <input type='password' name='password' value=''></p>

        <p><label>Confirm Password</label><br />
            <input type='password' name='passwordConfirm' value=''></p>

        <p><input type='submit' name='submit' value='Update Admin'></p>

    </form>


</div>

