<?php //include config
include 'app/views/admin/includes/admin-header.phtml';

//if not logged in redirect to login page
//if(!$user->is_logged_in()){ header('Location: login.php'); }
?>
<meta HTTP-EQUIV="Pragma" content="no-cache">
<meta HTTP-EQUIV="Expires" content="-1" >
<div id="wrapper">

    <h2>Edit Category</h2>
    <ul id='adminmenu'>
        <li><a href='/adBlog/index'>post</a></li>
        <li><a href="/adBlog/categories">categories</a></li>
    </ul>
    <div class='clear'></div>
    <hr />
    <?php

    //check for any errors
    if(isset($this->view_data['error'])){
        foreach($this->view_data['error'] as $error1){
            echo '<p class="error">'.$error1.'</p>';
        }
    }
    ?>


    <form action='' method='post'>

        <p><label>Title</label><br />
            <input type='text' name='catTitle' value='<?php echo $this->view_data['category'][0]['name'] ?>'></p>

        <p><label>Description</label><br />
            <input type='text' name='catDesc' value='<?php echo $this->view_data['category'][0]['description'] ?>'></p>

        <p><input type='submit' name='submit' value='Submit'></p>

    </form>


</div>
