<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Admin Login</title>
    <link rel="stylesheet" href="/app/helpers/css/bootstrap.min.css">
    <!-- Bootstrap style -->
    <link rel="stylesheet" href="/app/helpers/css/templatemo-style.css">
</head>
<body>

<div id="login">
    <?php

    //check for any errors
    if(isset($this->view_data['error'])){
        foreach($this->view_data['error'] as $error1){
            echo '<p class="error">'.$error1.'</p>';
        }
    }
    ?>
	<form action="" method="post">
	<p><label>Username</label><input type="text" name="username" value=""  /></p>
	<p><label>Password</label><input type="password" name="password" value=""  /></p>
	<p><label></label><input type="submit" name="submit" value="Login"  /></p>
	</form>
    <p><a href="/home/index">Go to site</a></p>
</div>



