<?php include 'app/views/includes/header.phtml'?>
<div class="tm-about-img-container" style="background-image: url('<?php echo $this->view_data['headImage'];?>');">
</div>

<section class="tm-section">
    <div class="container-fluid">
        <div class="row tm-2-rows-sm-swap">

            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-9 tm-2-rows-sm-down-1">
                <h3 class="tm-gold-text"><?php echo $this->view_data['aboutUs'][0]['header']?></h3>
                <p><?php echo $this->view_data['aboutUs'][0]['keywords']?></p>
                <p><?php echo $this->view_data['aboutUs'][0]['content']?></p>
            </div>
        </div>

        <div class="row tm-margin-t-mid">
            <div class="col-xs-12">
                <h3 class="tm-gold-text"><?php echo $this->view_data['aboutUs'][1]['header']?></h3>
                <p><?php echo $this->view_data['aboutUs'][1]['keywords']?></p>
                <p><?php echo $this->view_data['aboutUs'][1]['content']?></p>
            </div>
        </div>
    </div>
</section>
    <?php include 'app/views/includes/footer.phtml'?>
