<?php include 'app/views/includes/header.phtml';?>

<div class="tm-blog-img-container" style="background-image: url('<?php echo $this->view_data['headImage'];?>');">

</div>

<section class="tm-section">
    <div class="container-fluid">
        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-9">
                <div class="tm-blog-post">
                    <h3 class="tm-gold-text"><?php echo $this->view_data['posts'][0]['title']; ?></h3>
                    <p><?php echo $this->view_data['posts'][0]['summary'];?></p>
                    <img src="<?php echo $this->view_data['posts'][0]['image'];?>" alt="Image" class="img-fluid tm-img-post">

                    <p>
                        <?php echo $this->view_data['posts'][0]['content'];?>
                    </p>
                </div>
                <br><hr><br>
                <div class="row tm-margin-t-big">
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">

                        <div class="tm-content-box">
                            <img src="<?php echo $this->view_data['posts'][1]['image'];?>" alt="Image" class="tm-margin-b-30 img-fluid">
                            <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $this->view_data['posts'][1]['title'];?></h4>
                            <p class="tm-margin-b-20"><?php echo $this->view_data['posts'][1]['summary'];?></p>
                            <a href="<?php echo "/home/blog/read/".$this->view_data['posts'][1]['id'] ?>" class="tm-btn text-uppercase">Detail</a>
                        </div>

                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">

                        <div class="tm-content-box">
                            <img src="<?php echo $this->view_data['posts'][2]['image'];?>" alt="Image" class="tm-margin-b-30 img-fluid">
                            <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $this->view_data['posts'][2]['title'];?></h4>
                            <p class="tm-margin-b-20"><?php echo $this->view_data['posts'][2]['summary'];?></p>
                            <a href="<?php echo "/home/blog/read/".$this->view_data['posts'][2]['id'] ?>" class="tm-btn text-uppercase">Read More</a>
                        </div>

                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">

                        <div class="tm-content-box">
                            <img src="<?php echo $this->view_data['posts'][3]['image'];?>" alt="Image" class="tm-margin-b-30 img-fluid">
                            <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $this->view_data['posts'][3]['title'];?></h4>
                            <p class="tm-margin-b-20"><?php echo $this->view_data['posts'][3]['summary'];?></p>
                            <a href="<?php echo "/home/blog/read/".$this->view_data['posts'][3]['id'] ?>" class="tm-btn text-uppercase">Detail</a>
                        </div>

                    </div>
                </div>

            </div>

            <aside class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 tm-aside-r" style="position: sticky">

                <div class="tm-aside-container">
                    <h3 class="tm-gold-text tm-title">
                        Categories
                    </h3>
                    <nav>
                        <ul class="nav">
                            <?php foreach ($this->view_data['categories'] as $category){?>
                                <li><a href="<?php echo '/home/blog/'.$category;?>" class="tm-text-link"><?php echo str_replace('-',' ',$category) ?></a></li>
                            <?php }?>
                        </ul>
                    </nav>

                </div>


            </aside>

        </div>

    </div>
</section>
<?php include 'app/views/includes/footer.phtml'?>
