<?php include 'app/views/includes/header.phtml';?>

<div class="tm-blog-img-container" style="background-image: url('<?php echo $this->view_data['headImage'];?>');">

</div>

<section class="tm-section">
    <div class="container-fluid">
        <div class="row">

            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-9">

                <div class="row tm-margin-t-big">
                    <?php foreach ($this->view_data['post'] as $post){ ?>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">

                        <div class="tm-content-box">
                            <img src="<?php echo $post['image']?>" alt="Image" class="tm-margin-b-30 img-fluid">
                            <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $post['title']?></h4>
                            <p class="tm-margin-b-20"><?php echo $post['summary']?></p>
                            <a href="<?php echo "/home/blog/read/".$post['id']?>" class="tm-btn text-uppercase">Detail</a>
                        </div>

                    </div>
                    <?php } ?>

                </div>

            </div>

            <aside class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 tm-aside-r">

                <div class="tm-aside-container">
                    <h3 class="tm-gold-text tm-title">
                        Categories
                    </h3>
                    <nav>
                        <ul class="nav">
                            <?php foreach ($this->view_data['categories'] as $category){?>
                                <li><a href="<?php echo '/home/blog/'.$category;?>" class="tm-text-link"><?php echo str_replace('-',' ',$category) ?></a></li>
                            <?php }?>
                        </ul>
                    </nav>

                </div>


            </aside>

        </div>

    </div>
</section>
<?php include 'app/views/includes/footer.phtml'?>
