<?php include 'app/views/includes/header.phtml';
?>
<div class="tm-home-img-container" style="background-image: url('<?php echo $this->view_data['headImage'];?>');">
    <img src="/app/helpers/img/tm-home-img.jpg" alt="Image" class="hidden-lg-up img-fluid">
</div>

<section class="tm-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-xs-center">
                <h2 class="tm-gold-text tm-title"><?php echo $this->view_data['intro'][0]['title'];?></h2>
                <p class="tm-subtitle"><?php echo $this->view_data['intro'][0]['content'];?></p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                <div class="tm-content-box">
                    <img src="<?php echo $this->view_data['intro'][1]['image'] ?>" alt="Image" class="tm-margin-b-20 img-fluid">
                    <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $this->view_data['intro']['1']['title']; ?></h4>
                    <p class="tm-margin-b-20"><?php echo $this->view_data['intro']['1']['content']; ?></p>
                    <a href="#" class="tm-btn text-uppercase">Detail</a>
                </div>

            </div>

            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                <div class="tm-content-box">
                    <img src="<?php echo $this->view_data['intro'][2]['image'] ?>" alt="Image" class="tm-margin-b-20 img-fluid">
                    <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $this->view_data['intro']['2']['title'];?></h4>
                    <p class="tm-margin-b-20"><?php echo $this->view_data['intro']['2']['content']; ?></p>
                    <a href="#" class="tm-btn text-uppercase">Read More</a>
                </div>

            </div>

            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                <div class="tm-content-box">
                    <img src="<?php echo $this->view_data['intro'][3]['image'] ?>" alt="Image" class="tm-margin-b-20 img-fluid">
                    <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $this->view_data['intro']['3']['title']; ?></h4>
                    <p class="tm-margin-b-20"><?php echo $this->view_data['intro']['3']['content']; ?></p>
                    <a href="#" class="tm-btn text-uppercase">Detail</a>
                </div>

            </div>

            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">

                <div class="tm-content-box">
                    <img src="<?php echo $this->view_data['intro'][4]['image'] ?>" alt="Image" class="tm-margin-b-20 img-fluid">
                    <h4 class="tm-margin-b-20 tm-gold-text"><?php echo $this->view_data['intro']['4']['title']; ?></h4>
                    <p class="tm-margin-b-20"><?php echo $this->view_data['intro']['4']['content']; ?></p>
                    <a href="#" class="tm-btn text-uppercase">Read More</a>
                </div>

            </div>
        </div> <!-- row -->

        <div class="row tm-margin-t-big">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                <div class="tm-2-col-left">
                    <div class="tm-2-rows-md-swap">
                        <div class="tm-overflow-auto row tm-2-rows-md-down-2">
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 tm-xs-m-t">
                                <h3 class="tm-gold-text tm-title">
                                    Useful Links
                                </h3>
                                <nav>
                                    <ul class="nav">
                                        <li><a href="#" class="tm-text-link">Suspendisse sed dui nulla</a></li>
                                        <li><a href="#" class="tm-text-link">Lorem ipsum dolor sit</a></li>
                                        <li><a href="#" class="tm-text-link">Duiss nec purus et eros</a></li>
                                        <li><a href="#" class="tm-text-link">Etiam pulvinar et ligula sed</a></li>
                                        <li><a href="#" class="tm-text-link">Proin egestas eu felis et iaculis</a></li>
                                    </ul>
                                </nav>
                            </div> <!-- col -->
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">

                <div class="tm-2-col-right">

                    <div class="row tm-2-rows-md-down-1 tm-margin-t-mid">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                            <h3 class="tm-gold-text tm-title tm-margin-b-30">Posts</h3>
                            <div class="media tm-related-post">
                                <div class="media-left media-middle">
                                    <a href="<?php echo '/home/blog/read/'.$this->view_data['posts'][0]['id'] ?>">
                                        <img class="media-object" src="<?php echo $this->view_data['posts'][0]['image']; ?>" alt="Generic placehoAenean cursus tellus mauris, quis consequat mauris dapibus id. Donec scelerisque porttitor pharetra.lder image">
                                    </a>
                                </div>
                                <div class="media-body">
                                    <a href="<?php echo '/home/blog/read/'.$this->view_data['posts'][0]['id'] ?>"><h4 class="media-heading tm-gold-text tm-margin-b-15"><?php echo $this->view_data['posts'][0]['title']; ?></h4></a>
                                    <p class="tm-small-font tm-media-description"><?php echo $this->view_data['posts'][0]['summary']; ?></p>
                                </div>
                            </div>

                            <div class="media tm-related-post">
                                <div class="media-left media-middle">
                                    <a href="<?php echo '/home/blog/read/'.$this->view_data['posts'][1]['id'] ?>">
                                        <img class="media-object" src="<?php echo $this->view_data['posts'][1]['image']; ?>" alt="Generic placeholder image">
                                    </a>
                                </div>
                                <div class="media-body">
                                    <a href="<?php echo '/home/blog/read/'.$this->view_data['posts'][1]['id'] ?>"><h4 class="media-heading tm-gold-text tm-margin-b-15"><?php echo $this->view_data['posts'][1]['title']; ?></h4></a>
                                    <p class="tm-small-font tm-media-description"><?php echo $this->view_data['posts'][1]['summary']; ?></p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div> <!-- row -->

    </div>
</section>
<?php include 'app/views/includes/footer.phtml'?>